# Generated by Django 4.2.5 on 2023-10-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team4db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_naver',
            name='published_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='train_snu',
            name='published_date',
            field=models.TextField(null=True),
        ),
    ]
